stages:
  data_ingestion:
    cmd:
      python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
    outs:
      - artifacts/data.csv
      - artifacts/train.csv
      - artifacts/test.csv
  
  data_transformation:
    cmd:
      python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - artifacts/data.csv
    outs:
      - artifacts/transformer.pkl

  model_training:
    cmd:
      python -m src.components.model_trainer
    deps:
      - src/components/model_trainer.py
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/transformer.pkl
    outs:
      - artifacts/model.pkl